name: Send Daily CS:GO Update

on:
  schedule:
    - cron: "0 8 * * *"  # Every day at 8:00 AM UTC
  workflow_dispatch:     # Optional: lets you trigger it manually from GitHub

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the Telegram bot script
        run: python main.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
      - name: Commit JSON update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add historical_data.json
          git commit -m "Update history.json [skip ci]" || echo "No changes to commit"
          git push
